[pytest]
# 添加命令行参数,生成allure报告
;addopts = -s --alluredir=../data/report/results-%Y%m%d%H%M%S
addopts = -vs --strict -p no:warnings -p no:faulthandler
# 定义时间戳目录变量
[allure]
results_directory = {tmp_path}/allure-results-{now:%Y-%m-%d_%H-%M-%S}

# allure报告生成命令
# 手动执行生成命令 allure generate .\report\results\ -o .\report\html --clean
command = allure generate {allure_results_directory} -o {report_path} --clean

# allure报告输出目录
report_path = {sys.path[0]}/src/report